"""Auto-generated by scripts/regen_vendor_integrity.py.
Do not edit by hand — re-run the script after updating any
vendor file."""
from __future__ import annotations

SRI_HASHES: dict[str, str] = {
    "vendor/cropperjs/cropper.min.css": "sha384-6LFfkTKLRlzFtgx8xsWyBdKGpcMMQTkv+dB7rAbugeJAu1Ym2q1Aji1cjHBG12Xh",
    "vendor/cropperjs/cropper.min.js": "sha384-jrOgQzBlDeUNdmQn3rUt/PZD+pdcRBdWd/HWRqRo+n2OR2QtGyjSaJC0GiCeH+ir",
    "vendor/photoswipe/photoswipe-lightbox.umd.min.js": "sha384-IiBVbUz6+U+Tbm/ijO2P0XRwcVzNfrMzloNLkrqHkbi6w5H0v6ie4fI9BIO4SwdK",
    "vendor/photoswipe/photoswipe.css": "sha384-s2AldnnzPSlbjXKTGuicXrolvAtPwQBv9ndvaRLccssYIi3A2bjWOv3p+poD8LUk",
    "vendor/photoswipe/photoswipe.umd.min.js": "sha384-k8EKyYcONphQ7zH4cQ0888JapXwrLTXQl/Ue1/jYgjVYahln1NWpnt2S4IC56LNh",
}
