#!/usr/bin/env python3
"""Regenerate flexlog/static/vendor/INTEGRITY.txt + flexlog/web/vendor_integrity.py.

INTEGRITY.txt is the sha256sum-format manifest verified at install
time. vendor_integrity.py is the sha384-base64 dict that Jinja
templates consume via the vendor_sri filter to emit integrity=""
attributes on <script>/<link> tags.

Run after updating any vendor file:
    python scripts/regen_vendor_integrity.py
"""
from __future__ import annotations

import base64
import hashlib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
VENDOR_DIR = ROOT / "flexlog" / "static" / "vendor"
INTEGRITY_TXT = VENDOR_DIR / "INTEGRITY.txt"
PY_MODULE = ROOT / "flexlog" / "web" / "vendor_integrity.py"


def vendor_files() -> list[Path]:
    """Every regular file under flexlog/static/vendor/, excluding
    INTEGRITY.txt and any dotfile (.DS_Store, .gitkeep, etc.).
    Returns paths sorted for deterministic output."""
    files = [
        p for p in VENDOR_DIR.rglob("*")
        if p.is_file()
        and p.name != "INTEGRITY.txt"
        and not p.name.startswith(".")
    ]
    return sorted(files, key=lambda p: p.relative_to(VENDOR_DIR).as_posix())


def sha256_hex(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def sha384_base64(path: Path) -> str:
    h = hashlib.sha384()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return base64.b64encode(h.digest()).decode("ascii")


def main() -> int:
    files = vendor_files()
    if not files:
        print(f"no vendor files found under {VENDOR_DIR}")
        return 1

    # 1. Write INTEGRITY.txt (sha256sum -c compatible format).
    integrity_lines = []
    for p in files:
        rel = p.relative_to(VENDOR_DIR).as_posix()
        integrity_lines.append(f"{sha256_hex(p)}  {rel}\n")
    INTEGRITY_TXT.write_text("".join(integrity_lines), encoding="utf-8")
    print(f"wrote {INTEGRITY_TXT} ({len(files)} files)")

    # 2. Write vendor_integrity.py (sha384 base64, for SRI in templates).
    sri_entries = []
    for p in files:
        # Templates use static/-relative paths like "vendor/photoswipe/..."
        rel = p.relative_to(VENDOR_DIR.parent).as_posix()
        sri_entries.append(
            f'    "{rel}": "sha384-{sha384_base64(p)}",\n'
        )
    py_body = (
        '"""Auto-generated by scripts/regen_vendor_integrity.py.\n'
        'Do not edit by hand — re-run the script after updating any\n'
        'vendor file."""\n'
        'from __future__ import annotations\n\n'
        'SRI_HASHES: dict[str, str] = {\n'
        f'{"".join(sri_entries)}'
        '}\n'
    )
    PY_MODULE.write_text(py_body, encoding="utf-8")
    print(f"wrote {PY_MODULE}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
